language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
#install: "pip install pelican Markdown --use-mirrors"
# command to run tests
script: PYTHONPATH=./packages.zip nosetests -s
